-- Cited, machine-derived specs extracted from FCC Schedule S Tech Reports.
--
-- Schedule S Tech Reports are generated by the FCC's own filing tool, not typed by applicants, so
-- the layout is fixed label-value and the values are exact. These fields are therefore parsed
-- deterministically: no model, no inference. A regex reads the same bytes a human would, and
-- cannot produce a plausible-but-wrong number, which is the failure a language model would make
-- here and the one this project can least afford.
--
-- Every row carries the document it came from, that document's content hash, and the physical page
-- the value appears on. ingest/spec_validate.py then re-opens that page and confirms the value's
-- tokens are physically present before is_validated flips true. Extraction and validation are
-- separate code paths on purpose: the worst failure available to this layer is not a missing
-- altitude, it is a plausible citation pointing at a page that does not support it, because that
-- discredits every other cited figure on the platform.
--
-- Planes are stored RAW, one row per orbital plane as Schedule S lists them. "Shell" is a derived
-- grouping with its own judgement attached, and it is deliberately not stored here; any rollup must
-- cite these rows and record the grouping rule it used.
--
-- This layer is machine-derived and stays out of headline metrics, inheriting the rule that keeps
-- pending FCC applications informational and detail-page-only (BUS_BENCHMARKS_METHODOLOGY 5.8).
--
-- Coverage is bounded and should be published as such: Schedule S exists for 65 of the 136 filings
-- with a harvested document inventory. For filings that have only a narrative, orbital parameters
-- are very likely not in the corpus at all -- narratives carry intent and legal argument, and were
-- measured to contain no numeric orbital parameters.

CREATE TABLE IF NOT EXISTS fcc_filing_blob (
    file_number   TEXT NOT NULL,
    sys_id        TEXT NOT NULL,
    sha256        TEXT,
    byte_count    BIGINT,
    content_type  TEXT,
    page_count    INT,
    -- ok | http_error | truncated | parse_error.  'truncated' is kept distinct from 'parse_error'
    -- on purpose: the gateway serves some attachments partially, answering 200 with
    -- content-type application/pdf and only the opening bytes (measured: all 28 documents of
    -- SATLOA2016062200058 come back as exactly 455 bytes against a declared length of 87,684, and
    -- it is server-side -- identity, gzip, curl and curl_cffi all get the same). That is the FCC's
    -- data being unavailable, which belongs in published coverage. A parse failure on complete
    -- bytes would be our defect. Collapsing the two would hide which is which.
    fetch_status  TEXT NOT NULL,
    fetch_note    TEXT,
    fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (file_number, sys_id)
);

CREATE TABLE IF NOT EXISTS fcc_spec_filing (
    file_number       TEXT PRIMARY KEY,
    sys_id            TEXT NOT NULL,
    doc_sha256        TEXT NOT NULL,
    -- Column names match parse_scalars() output keys exactly (it emits f"{key}_page"), so the
    -- loader is a straight dict-to-column map with no renaming layer to drift out of sync.
    orbit_type             TEXT,           -- NGSO | GSO, verbatim from 'Select Orbit Type'
    orbit_type_page        INT,
    network_name           TEXT,
    network_name_page      INT,
    lifetime_years         NUMERIC,
    lifetime_years_page    INT,
    total_satellites       INT,
    total_satellites_page  INT,
    extractor_version TEXT NOT NULL,
    run_id            BIGINT,
    is_validated      BOOLEAN NOT NULL DEFAULT false,
    extracted_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Citations here are PER FIELD, not per row, and that is not fastidiousness. A plane's four values
-- routinely straddle a page break in real filings: measured on SATAMD2017030100030, 17 of 74 planes
-- have their inclination on one page and their apogee and perigee on the next. A single row-level
-- page number is therefore wrong for a quarter of the corpus, and wrong in the worst available
-- direction, because it points a reader at a real page that does not contain the value.
CREATE TABLE IF NOT EXISTS fcc_spec_orbital (
    file_number         TEXT NOT NULL,
    sys_id              TEXT NOT NULL,
    plane_idx           INT  NOT NULL,     -- ordinal within the document, not an FCC plane id
    apogee_km           NUMERIC,
    apogee_page         INT,
    perigee_km          NUMERIC,
    perigee_page        INT,
    inclination_deg     NUMERIC,
    inclination_page    INT,
    arg_perigee_deg     NUMERIC,
    arg_perigee_page    INT,
    source_page         INT NOT NULL,      -- where the plane begins; per-field pages are authoritative
    doc_sha256          TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    run_id            BIGINT,
    is_validated      BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (file_number, sys_id, plane_idx)
);

CREATE TABLE IF NOT EXISTS fcc_spec_band (
    file_number       TEXT NOT NULL,
    sys_id            TEXT NOT NULL,
    band_idx          INT  NOT NULL,
    service           TEXT,
    freq_low_mhz      NUMERIC,
    freq_high_mhz     NUMERIC,
    direction         TEXT,                -- Transmit | Receive
    source_page       INT NOT NULL,
    doc_sha256        TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    run_id            BIGINT,
    is_validated      BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (file_number, sys_id, band_idx)
);

CREATE INDEX IF NOT EXISTS fcc_spec_orbital_file ON fcc_spec_orbital (file_number);
CREATE INDEX IF NOT EXISTS fcc_spec_band_file    ON fcc_spec_band (file_number);
