"""Deterministic parser for FCC Schedule S Tech Report PDFs.

These reports are generated by the FCC's filing tool, not typed by applicants, so the layout is
fixed and the values are exact. That makes a regex strictly better than a language model here: it
costs the same as reading the file, and it cannot invent a plausible-but-wrong number, which is the
one failure this platform cannot absorb. A model earns its place later, on the prose fields that
genuinely are prose -- deorbit commitments, waiver language -- not on numbers sitting in a table.

Detection deliberately does NOT key on "Schedule S" or "Form 312". Neither string appears anywhere
in the generated report; they live on the blank form. Anchoring on them matched 0 of 3 real
harvested documents. The anchors below were read off the documents themselves and match 3 of 3.

The parser abstains rather than guesses. A field it cannot find comes back None with no page
number, because a citation attached to a guessed value is worse than no value at all.
"""

from __future__ import annotations

import re

EXTRACTOR_VERSION = "schedule_s/1.0"

# Verified present in every sampled Tech Report and absent from narratives. Two of three are
# required, so a single layout change or a text-extraction hiccup does not silently drop a document.
_ANCHORS = ("OMB 3060-0678", "312 File Number:", "Select Orbit Type")

_SCALARS = {
    "orbit_type": re.compile(r"Select Orbit Type\s+(NGSO|GSO)\b", re.I),
    "network_name": re.compile(r"Space Station or Satellite Network Name\s+(.+?)\s*$", re.M),
    "lifetime_years": re.compile(
        r"Estimated Lifetime of Satellite\(s\) From Date of Launch\s+(\d+(?:\.\d+)?)\s*Years?",
        re.I,
    ),
    "total_satellites": re.compile(
        r"Total Number of Satellites in the active constellation\s+(\d+)", re.I
    ),
}
_NUMERIC = {"lifetime_years": float, "total_satellites": int}

_ORBIT_FIELDS = {
    "Inclination Angle": ("inclination_deg", "degrees"),
    "Argument of Perigee": ("arg_perigee_deg", "degrees"),
    "Apogee": ("apogee_km", "km"),
    "Perigee": ("perigee_km", "km"),
}
# Each orbital value carries its own page, because a plane's fields straddle page breaks.
_PAGE_KEY = {
    "inclination_deg": "inclination_page",
    "arg_perigee_deg": "arg_perigee_page",
    "apogee_km": "apogee_page",
    "perigee_km": "perigee_page",
}

# Anchored on the unit so prose can never match. A narrative saying "at low and very low altitudes"
# has no number and no unit, and that is exactly the sentence that would otherwise become data.
_ORBIT_LINE = re.compile(
    r"^\s*(Inclination Angle|Argument of Perigee|Apogee|Perigee)\s+"
    r"(-?\d+(?:\.\d+)?)\s+(degrees|km)\s*$",
    re.M,
)

# The frequency table renders ONE CELL PER LINE under pypdf, not one row per line, so a band's
# service / range / direction arrive as five or more separate lines and a wrapped service label
# ("Earth Exploration-Satellite" then "Service") is split across two of them. The service group
# therefore has to admit newlines, and the match is whitespace-joined afterwards. Without that the
# capture silently keeps only the trailing fragment, "Service", which still passes citation
# validation because that word genuinely is on the page -- presence is not completeness.
_BAND_LINE = re.compile(
    r"(?P<service>[A-Za-z][A-Za-z ,'/()-]{0,44}(?:\n[A-Za-z][A-Za-z ,'/()-]{0,44})?)\s+"
    r"(?P<low>\d+(?:\.\d+)?)\s*MHz\s*-\s*(?P<high>\d+(?:\.\d+)?)\s*MHz\s+"
    r"(?P<direction>Transmit|Receive)\b",
)


def is_schedule_s(pages: list[str]) -> bool:
    """True when the document is a Schedule S Tech Report, judged by content rather than filename.

    Filenames are not trustworthy here: the corpus carries 558 distinct doc_name values for 1,307
    documents. Name selects candidates; this decides.
    """
    head = "\n".join(pages[:3])
    return sum(1 for anchor in _ANCHORS if anchor in head) >= 2


def parse_scalars(pages: list[str]) -> dict:
    """Per-filing scalar fields, each paired with the physical page it was found on.

    Keys are emitted as `<field>` and `<field>_page`, and the fcc_spec_filing columns are named to
    match exactly, so the loader is a straight dict-to-column map with nothing in between to drift.
    """
    out: dict = {}
    for key, pattern in _SCALARS.items():
        out[key] = None
        out[f"{key}_page"] = None
        for page_no, text in enumerate(pages, start=1):
            match = pattern.search(text)
            if not match:
                continue
            raw = match.group(1).strip()
            cast = _NUMERIC.get(key)
            out[key] = cast(raw) if cast else raw
            out[f"{key}_page"] = page_no
            break
    return out


def parse_planes(pages: list[str]) -> list[dict]:
    """One row per orbital plane, in document order.

    A plane closes when a field repeats: the report emits the same four labels per plane, so a
    second 'Inclination Angle' means a new plane began. Shells are NOT derived here. Grouping planes
    into shells is a judgement with its own rule, and whatever makes that call has to cite these
    rows rather than silently bake the rule into the data.

    Each field carries its OWN page. A plane's four values routinely straddle a page break: on
    SATAMD2017030100030, 17 of 74 planes have their inclination on one page and their apogee and
    perigee on the next. A single row-level page would be wrong for a quarter of that document, and
    wrong in the worst direction, since it points a reader at a real page lacking the value.
    `source_page` is kept as where the plane begins, but the per-field pages are authoritative.
    """
    planes: list[dict] = []
    current: dict = {}
    for page_no, text in enumerate(pages, start=1):
        for label, value, unit in _ORBIT_LINE.findall(text):
            key, want_unit = _ORBIT_FIELDS[label]
            if unit != want_unit:
                continue
            if key in current:
                planes.append(current)
                current = {"source_page": page_no}
            current.setdefault("source_page", page_no)
            current[key] = float(value)
            current[_PAGE_KEY[key]] = page_no
    if current and any(k in current for k in ("apogee_km", "inclination_deg")):
        planes.append(current)
    for idx, plane in enumerate(planes):
        plane["plane_idx"] = idx
    return planes


def parse_bands(pages: list[str]) -> list[dict]:
    """One row per operating frequency band, with its direction.

    Rows rather than a text array on purpose: a band has a service, a range and a direction, and
    collapsing that into a string would make it unqueryable and uncitable at the field level.
    """
    bands: list[dict] = []
    for page_no, text in enumerate(pages, start=1):
        for match in _BAND_LINE.finditer(text):
            bands.append({
                "band_idx": len(bands),
                # Whitespace-joined because the label may have wrapped across table lines.
                "service": " ".join(match.group("service").split()),
                "freq_low_mhz": float(match.group("low")),
                "freq_high_mhz": float(match.group("high")),
                "direction": match.group("direction"),
                "source_page": page_no,
            })
    return bands
